// Generated by tools/set-login.mjs - do not edit by hand.
// Contains only a salted PBKDF2 hash; the real username/password are not stored here.
window.SICONVERSE_LOGIN = {"version":1,"iterations":150000,"salt":"6tRxA6uxKpRneTx1NJHbAA==","hash":"ddGrPBVzQazXSAySLGKRKHouKVQ64qV97kRoOD92oGw="};
