#!/usr/bin/env node
// Owner tool: set the shared Siconverse username/password (about every 6 months).
// Usage (from the repo root):  node tools/set-login.mjs
// Asks for the values interactively; writes login/credentials.js with a salted
// PBKDF2 hash only. The real username/password are never written anywhere.
import { webcrypto, randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import readline from 'node:readline';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
if (!globalThis.crypto) globalThis.crypto = webcrypto;
const auth = require(path.join(root, 'login', 'auth.js'));

export const ITERATIONS = 150000;
export const CREDENTIALS_PATH = path.join(root, 'login', 'credentials.js');

export async function buildCredentials(username, password, opts = {}) {
    if (!auth.normalizeUser(username)) throw new Error('Username must not be empty');
    if (!password) throw new Error('Password must not be empty');
    const cfg = {
        version: opts.version || 1,
        iterations: opts.iterations || ITERATIONS,
        salt: opts.salt || randomBytes(16).toString('base64'),
    };
    cfg.hash = await auth.derive(username, password, cfg);
    return cfg;
}

export function renderCredentials(cfg) {
    return '// Generated by tools/set-login.mjs - do not edit by hand.\n' +
        '// Contains only a salted PBKDF2 hash; the real username/password are not stored here.\n' +
        'window.SICONVERSE_LOGIN = ' + JSON.stringify(cfg) + ';\n';
}

export function readVersion(file = CREDENTIALS_PATH) {
    if (!existsSync(file)) return 0;
    const m = /"version":(\d+)/.exec(readFileSync(file, 'utf8'));
    return m ? Number(m[1]) : 0;
}

function ask(rl, question, hidden) {
    return new Promise(resolve => {
        if (!hidden) return rl.question(question, resolve);
        const write = rl._writeToOutput.bind(rl);
        rl._writeToOutput = s => write(s.includes(question) ? s : '*');
        rl.question(question, answer => { rl._writeToOutput = write; process.stdout.write('\n'); resolve(answer); });
    });
}

async function main() {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout, terminal: true });
    const username = await ask(rl, 'Username: ', false);
    const password = await ask(rl, 'Password: ', true);
    const again = await ask(rl, 'Password again: ', true);
    rl.close();
    if (password !== again) { console.error('Passwords do not match. Nothing changed.'); process.exit(1); }
    const cfg = await buildCredentials(username, password, { version: readVersion() + 1 });
    writeFileSync(CREDENTIALS_PATH, renderCredentials(cfg));
    console.log(`Wrote login/credentials.js (version ${cfg.version}). Everyone must log in again after deploy.`);
    console.log('Next: git add login/credentials.js && git commit -m "chore: rotate Siconverse login" && git push');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    main().catch(err => { console.error(err.message); process.exit(1); });
}
